#!/usr/bin/env node
/**
 * embed-assets.mjs — base64-embed the INT8 model and bake in the real labels +
 * preprocessing, overwriting src/assets.generated.ts (EMBEDDED = true).
 *
 * Inputs (produced by scripts/export_model.py):
 *   model/nsfw.int8.onnx
 *   model/labels.json
 *   model/preprocess.json
 *
 * Run:  npm run embed-model   (then `npm run build`)
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const MODEL_PATH = resolve(root, "model", "nsfw.int8.onnx");
const LABELS_PATH = resolve(root, "model", "labels.json");
const PREPROCESS_PATH = resolve(root, "model", "preprocess.json");
const OUT_PATH = resolve(root, "src", "assets.generated.ts");

function die(msg) {
  console.error(`[embed] ERROR: ${msg}`);
  process.exit(1);
}

if (!existsSync(MODEL_PATH)) {
  die(
    `${MODEL_PATH} not found.\n` +
      "        Run the export pipeline first:\n" +
      "          python scripts/export_model.py   (after training)\n"
  );
}

const modelBytes = readFileSync(MODEL_PATH);
const modelB64 = modelBytes.toString("base64");
const mb = (modelBytes.length / (1024 * 1024)).toFixed(2);

let labels = [];
if (existsSync(LABELS_PATH)) {
  labels = JSON.parse(readFileSync(LABELS_PATH, "utf8"));
} else {
  console.warn(`[embed] WARN: ${LABELS_PATH} missing — embedding empty labels (fallback will be used).`);
}

let preprocess = {};
if (existsSync(PREPROCESS_PATH)) {
  preprocess = JSON.parse(readFileSync(PREPROCESS_PATH, "utf8"));
} else {
  console.warn(`[embed] WARN: ${PREPROCESS_PATH} missing — embedding empty preprocess (fallback will be used).`);
}

// Sanity: the binary head must classify two named classes including "nsfw".
const lower = labels.map((l) => String(l).toLowerCase());
if (labels.length && !lower.includes("nsfw")) {
  console.warn(
    `[embed] WARN: labels ${JSON.stringify(labels)} do not include "nsfw"; ` +
      "gating reads the nsfw class by name and will always read 0."
  );
}
if (labels.length && labels.length !== 2) {
  console.warn(`[embed] WARN: expected 2 labels for a binary model, got ${labels.length}: ${JSON.stringify(labels)}`);
}

const banner = `/**
 * assets.generated.ts — AUTOGENERATED by scripts/embed-assets.mjs. Do not edit.
 * Model: ${mb} MB INT8 (base64). Labels: ${JSON.stringify(labels)}.
 */`;

const out = `${banner}
import type { PreprocessConfig } from "./types.js";

export const EMBEDDED = true;
export const LABELS: string[] = ${JSON.stringify(labels)};
export const PREPROCESS: Partial<PreprocessConfig> = ${JSON.stringify(preprocess)};
export const MODEL_B64 =
  "${modelB64}";
`;

writeFileSync(OUT_PATH, out);
console.log(`[embed] wrote ${OUT_PATH}`);
console.log(`[embed]   model : ${mb} MB INT8`);
console.log(`[embed]   labels: ${JSON.stringify(labels)}`);
console.log(`[embed]   preprocess.size = ${preprocess.size ?? "(fallback)"}`);
console.log("[embed] next: npm run build");
