#!/usr/bin/env node
/**
 * embed-assets.mjs — base64-embed the mnv4 uint8 ONNX model (plus its
 * labels.json / preprocess.json) into src/variants/mnv4/assets.generated.ts.
 *
 *   node scripts/embed-assets.mjs          # embed mnv4 (alias: npm run embed-model)
 *   node scripts/embed-assets.mjs mnv4     # same — mnv4 is the only variant
 *
 * The model is read from model/mnv4/ — matching the trainer's `--out-dir
 * model/mnv4` default. If model/mnv4/nsfw.uint8.onnx is missing, a stub
 * (EMBEDDED=false) is written so the build still compiles; the detector then
 * throws "no model is embedded" at runtime until you train + export + embed.
 *
 * Pipeline:
 *   python scripts/train_nsfw_hf_mnv4_160.py ...                      -> model/mnv4/nsfw_mnv4.pt (+ labels/preprocess)
 *   python scripts/export_model.py --variant mnv4 --calib-data <dir>  -> model/mnv4/nsfw.uint8.onnx
 *   npm run embed:mnv4           (or `npm run embed-model`)
 *   npm run build                                                     -> dist/mnv4/...
 *
 * NOTE: export_model.py also emits model/mnv4/nsfw.fp16.onnx (for the WebGPU EP).
 * This single-model bundle embeds the uint8 build, which runs on the WASM EP and
 * on WebGPU with per-op CPU fallback for the QDQ nodes. To embed + select the
 * fp16 model on WebGPU instead, the loader needs the dual-model path (see README).
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// mnv4 is the only variant this package ships.
const VARIANTS = ["mnv4"];
const MODEL_FILE = "nsfw.uint8.onnx";

const modelDir = (v) => join(ROOT, "model", v);
const variantDir = (v) => join(ROOT, "src", "variants", v);

function readJSON(path, fallback) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return fallback;
  }
}

const HEADER =
  "// AUTO-GENERATED by scripts/embed-assets.mjs — do not edit by hand.\n" +
  "// Re-run `npm run embed-model` (or `npm run embed:mnv4`) to refresh.\n";

function writeStub(v) {
  const dir = variantDir(v);
  mkdirSync(dir, { recursive: true });
  const body =
    HEADER +
    `// No model/${v}/${MODEL_FILE} found — shipping an EMPTY stub.\n` +
    '// The detector throws "no model is embedded" at runtime until you embed one.\n' +
    'export const MODEL_B64 = "";\n' +
    'export const LABELS: string[] = ["nsfw", "sfw"];\n' +
    "export const PREPROCESS: Record<string, unknown> = {};\n" +
    "export const EMBEDDED = false;\n";
  writeFileSync(join(dir, "assets.generated.ts"), body);
}

function writeEmbedded(v) {
  const md = modelDir(v);
  const bytes = readFileSync(join(md, MODEL_FILE));
  const b64 = bytes.toString("base64");
  const labels = readJSON(join(md, "labels.json"), ["nsfw", "sfw"]);
  const preprocess = readJSON(join(md, "preprocess.json"), {});
  const dir = variantDir(v);
  mkdirSync(dir, { recursive: true });
  const body =
    HEADER +
    `// Embedded from model/${v}/${MODEL_FILE} (${bytes.length} bytes).\n` +
    `export const MODEL_B64 = "${b64}";\n` +
    `export const LABELS: string[] = ${JSON.stringify(labels)};\n` +
    `export const PREPROCESS: Record<string, unknown> = ${JSON.stringify(preprocess)};\n` +
    "export const EMBEDDED = true;\n";
  writeFileSync(join(dir, "assets.generated.ts"), body);
  return { onnxBytes: bytes.length, labels };
}

const requested = process.argv.slice(2).filter(Boolean);
const targets = requested.length ? requested : VARIANTS;

let embedded = 0;
let stubbed = 0;
for (const v of targets) {
  if (!VARIANTS.includes(v)) {
    console.error(`[embed] unknown variant "${v}" (this package ships only: ${VARIANTS.join(", ")})`);
    process.exitCode = 1;
    continue;
  }
  if (existsSync(join(modelDir(v), MODEL_FILE))) {
    const { onnxBytes, labels } = writeEmbedded(v);
    const kb = (onnxBytes / 1024).toFixed(1);
    console.log(
      `[embed] ${v}: embedded ${kb} KB ONNX, labels=${JSON.stringify(labels)} ` +
        `-> src/variants/${v}/assets.generated.ts`
    );
    embedded++;
  } else {
    writeStub(v);
    console.log(`[embed] ${v}: no model/${v}/${MODEL_FILE} — wrote EMPTY stub (EMBEDDED=false)`);
    stubbed++;
  }
}
console.log(`[embed] done: ${embedded} embedded, ${stubbed} stubbed.`);
