#!/usr/bin/env node
/**
 * embed-assets.mjs — base64-embed each variant's INT8 ONNX model (plus its
 * labels.json / preprocess.json) into src/variants/<variant>/assets.generated.ts.
 *
 *   node scripts/embed-assets.mjs              # every variant that has a model
 *   node scripts/embed-assets.mjs mnv4 lcnet   # only the named variants
 *
 * Each variant reads from model/<variant>/ — matching the trainer's
 * `--out-dir model/<variant>` default. A variant with no
 * model/<variant>/nsfw.int8.onnx gets a stub (EMBEDDED=false) so the build
 * still compiles; that variant throws "no model is embedded" at runtime until
 * you train + export + embed it.
 *
 * Pipeline (per variant <v>):
 *   python scripts/train_nsfw_hf_<v>.py ...                   -> model/<v>/nsfw_<v>.pt (+ labels/preprocess)
 *   python scripts/export_model.py --checkpoint model/<v>/nsfw_<v>.pt \
 *          --calib-data <dir> --out-dir model/<v>             -> model/<v>/nsfw.int8.onnx
 *   npm run embed:<v>            (or `npm run embed-model` for all)
 *   npm run build                                             -> dist/<v>/...
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const VARIANTS = ["mnv4", "mnv3", "tinynet", "lcnet"];

const modelDir = (v) => join(ROOT, "model", v);
const variantDir = (v) => join(ROOT, "src", "variants", v);

function readJSON(path, fallback) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return fallback;
  }
}

const HEADER =
  "// AUTO-GENERATED by scripts/embed-assets.mjs — do not edit by hand.\n" +
  "// Re-run `npm run embed-model` (or `npm run embed:<variant>`) to refresh.\n";

function writeStub(v) {
  const dir = variantDir(v);
  mkdirSync(dir, { recursive: true });
  const body =
    HEADER +
    `// No model/${v}/nsfw.int8.onnx found — shipping an EMPTY stub.\n` +
    '// The detector throws "no model is embedded" at runtime until you embed one.\n' +
    'export const MODEL_B64 = "";\n' +
    'export const LABELS: string[] = ["nsfw", "sfw"];\n' +
    "export const PREPROCESS: Record<string, unknown> = {};\n" +
    "export const EMBEDDED = false;\n";
  writeFileSync(join(dir, "assets.generated.ts"), body);
}

function writeEmbedded(v) {
  const md = modelDir(v);
  const bytes = readFileSync(join(md, "nsfw.int8.onnx"));
  const b64 = bytes.toString("base64");
  const labels = readJSON(join(md, "labels.json"), ["nsfw", "sfw"]);
  const preprocess = readJSON(join(md, "preprocess.json"), {});
  const dir = variantDir(v);
  mkdirSync(dir, { recursive: true });
  const body =
    HEADER +
    `// Embedded from model/${v}/nsfw.int8.onnx (${bytes.length} bytes).\n` +
    `export const MODEL_B64 = "${b64}";\n` +
    `export const LABELS: string[] = ${JSON.stringify(labels)};\n` +
    `export const PREPROCESS: Record<string, unknown> = ${JSON.stringify(preprocess)};\n` +
    "export const EMBEDDED = true;\n";
  writeFileSync(join(dir, "assets.generated.ts"), body);
  return { onnxBytes: bytes.length, labels };
}

const requested = process.argv.slice(2).filter(Boolean);
const targets = requested.length ? requested : VARIANTS;

let embedded = 0;
let stubbed = 0;
for (const v of targets) {
  if (!VARIANTS.includes(v)) {
    console.error(`[embed] unknown variant "${v}" (known: ${VARIANTS.join(", ")})`);
    process.exitCode = 1;
    continue;
  }
  if (existsSync(join(modelDir(v), "nsfw.int8.onnx"))) {
    const { onnxBytes, labels } = writeEmbedded(v);
    const kb = (onnxBytes / 1024).toFixed(1);
    console.log(
      `[embed] ${v}: embedded ${kb} KB ONNX, labels=${JSON.stringify(labels)} ` +
        `-> src/variants/${v}/assets.generated.ts`
    );
    embedded++;
  } else {
    writeStub(v);
    console.log(
      `[embed] ${v}: no model/${v}/nsfw.int8.onnx — wrote EMPTY stub (EMBEDDED=false)`
    );
    stubbed++;
  }
}
console.log(`[embed] done: ${embedded} embedded, ${stubbed} stubbed.`);
